// <auto-generated />
using System;
using GradebookApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradebookApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006162325_PoprawkiPoprawIKalendarza")]
    partial class PoprawkiPoprawIKalendarza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("GradebookApp.PlannedRetake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WrittenWorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WrittenWorkId");

                    b.ToTable("PlannedRetakes");
                });

            modelBuilder.Entity("GradebookApp.PlannedRetakeStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedRetakeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlannedRetakeId");

                    b.HasIndex("StudentId");

                    b.ToTable("PlannedRetakeStudents");
                });

            modelBuilder.Entity("GradebookApp.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("GradebookApp.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AveragePercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JournalNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchoolClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GradebookApp.StudentTaskScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PointsLevel1")
                        .HasColumnType("REAL");

                    b.Property<double?>("PointsLevel2")
                        .HasColumnType("REAL");

                    b.Property<double?>("PointsLevel3")
                        .HasColumnType("REAL");

                    b.Property<double?>("RetakePointsLevel1")
                        .HasColumnType("REAL");

                    b.Property<double?>("RetakePointsLevel2")
                        .HasColumnType("REAL");

                    b.Property<double?>("RetakePointsLevel3")
                        .HasColumnType("REAL");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrittenWorkTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("WrittenWorkTaskId");

                    b.ToTable("StudentTaskScores");
                });

            modelBuilder.Entity("GradebookApp.StudentWorkRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CustomDateEntered")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CustomDateWritten")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetakeActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RetakeDateEntered")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetakeDateWritten")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetakeDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetakeGroup")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrittenWorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("WrittenWorkId");

                    b.ToTable("StudentWorkRecords");
                });

            modelBuilder.Entity("GradebookApp.WrittenWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateEntered")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateWritten")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasGroups")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IndividualStudentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIndividual")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxFinalPoints")
                        .HasColumnType("REAL");

                    b.Property<int>("SchoolClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("WrittenWorks");
                });

            modelBuilder.Entity("GradebookApp.WrittenWorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxPointsLevel1")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxPointsLevel2")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxPointsLevel3")
                        .HasColumnType("REAL");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrittenWorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WrittenWorkId");

                    b.ToTable("WrittenWorkTasks");
                });

            modelBuilder.Entity("StudentWrittenWork", b =>
                {
                    b.Property<int>("StudentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrittenWorksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentsId", "WrittenWorksId");

                    b.HasIndex("WrittenWorksId");

                    b.ToTable("StudentWrittenWork");
                });

            modelBuilder.Entity("GradebookApp.PlannedRetake", b =>
                {
                    b.HasOne("GradebookApp.WrittenWork", "WrittenWork")
                        .WithMany()
                        .HasForeignKey("WrittenWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WrittenWork");
                });

            modelBuilder.Entity("GradebookApp.PlannedRetakeStudent", b =>
                {
                    b.HasOne("GradebookApp.PlannedRetake", "PlannedRetake")
                        .WithMany("Attendees")
                        .HasForeignKey("PlannedRetakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradebookApp.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlannedRetake");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GradebookApp.Student", b =>
                {
                    b.HasOne("GradebookApp.SchoolClass", "SchoolClass")
                        .WithMany("Students")
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolClass");
                });

            modelBuilder.Entity("GradebookApp.StudentTaskScore", b =>
                {
                    b.HasOne("GradebookApp.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradebookApp.WrittenWorkTask", "WrittenWorkTask")
                        .WithMany()
                        .HasForeignKey("WrittenWorkTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("WrittenWorkTask");
                });

            modelBuilder.Entity("GradebookApp.StudentWorkRecord", b =>
                {
                    b.HasOne("GradebookApp.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradebookApp.WrittenWork", "WrittenWork")
                        .WithMany()
                        .HasForeignKey("WrittenWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("WrittenWork");
                });

            modelBuilder.Entity("GradebookApp.WrittenWork", b =>
                {
                    b.HasOne("GradebookApp.SchoolClass", "SchoolClass")
                        .WithMany("WrittenWorks")
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolClass");
                });

            modelBuilder.Entity("GradebookApp.WrittenWorkTask", b =>
                {
                    b.HasOne("GradebookApp.WrittenWork", "WrittenWork")
                        .WithMany("Tasks")
                        .HasForeignKey("WrittenWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WrittenWork");
                });

            modelBuilder.Entity("StudentWrittenWork", b =>
                {
                    b.HasOne("GradebookApp.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradebookApp.WrittenWork", null)
                        .WithMany()
                        .HasForeignKey("WrittenWorksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GradebookApp.PlannedRetake", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("GradebookApp.SchoolClass", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("WrittenWorks");
                });

            modelBuilder.Entity("GradebookApp.WrittenWork", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
